Add create invoice description
stripe/stripe-firebase-extensions pull request #231
Opened 2021-08-04 13:43 UTC by dackers86

fixes: https://github.com/stripe/stripe-firebase-extensions/issues/210

2021-08-04 13:43 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/stripe/stripe-firebase-extensions?pullRequest=231) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/stripe/stripe-firebase-extensions?pullRequest=231) before we can accept your contribution.<br/>**1** out of **3** committers have signed the CLA.<br/><br/>:white_check_mark: dackers86<br/>:x: jhuleatt<br/>:x: Alex Patterson<br/><hr/>**Alex Patterson** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/stripe/stripe-firebase-extensions?pullRequest=231) it.</sub>

2021-08-17 13:02 UTC, thorsten-stripe requested changes

2021-08-17 13:02 UTC, thorsten-stripe commented on firestore-stripe-invoices/functions/src/index.ts
> +  description = '',
I think this is missing the passing of the description from the payload though: https://github.com/stripe/stripe-firebase-extensions/blob/683551cb87197cd7e7d10bd1dbe737aacb7f9221/firestore-stripe-invoices/functions/src/index.ts#L169-L176

2021-08-18 10:15 UTC, dackers86 commented on firestore-stripe-invoices/functions/src/index.ts
> +  description = '',
Thanks. New commit added to add the missing description.

2021-08-18 15:17 UTC, thorsten-stripe approved these changes
LGTM, thanks

2021-08-25 03:59 UTC, merged