feat(firestore-stripe-invoices): Add `on_behalf_of` support for firestore invoices
stripe/stripe-firebase-extensions pull request #396
Opened 2022-06-06 15:28 UTC by Matttaylor8910

I'd like to propose updating the stripe version to support passing the `on_behalf_of` param to invoice creation, if present. When creating invoices via connect accounts, I'd like to be able to use those connected accounts branding and contact information.

2022-06-06 15:28 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/stripe/stripe-firebase-extensions?pullRequest=396) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/stripe/stripe-firebase-extensions?pullRequest=396) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/stripe/stripe-firebase-extensions?pullRequest=396) it.</sub>

2022-06-23 11:25 UTC, dackers86 requested changes

2022-06-23 11:28 UTC, dackers86 commented
Hi @Matttaylor8910. I've added some feedback to the PR.

2022-06-23 11:41 UTC, dackers86 requested changes

2022-06-23 11:41 UTC, dackers86 commented on firestore-stripe-invoices/functions/src/index.ts
> +  apiVersion: '2020-08-27',
Is this a required change for this feature. If, so other instances of `2020-03-02` will need to be updated. Otherwise, we can revert this change?

2022-08-23 11:37 UTC, jsteele-stripe commented on firestore-stripe-invoices/functions/src/index.ts
> +  on_behalf_of?: string;
@dackers86 This type _should_ be fine as we set a default value in the function signature: https://github.com/stripe/stripe-firebase-extensions/blob/2d368c50109536a2d1d5afb7e9f996bd10e1a613/firestore-stripe-invoices/functions/src/index.ts#L46

2023-03-20 10:43 UTC, closed without merging