Support payment_method_collection in Checkout Session
stripe/stripe-firebase-extensions pull request #495
Opened 2023-02-08 18:41 UTC by mattlrobinson7

Based on documentation https://stripe.com/docs/api/checkout/sessions/object#checkout_session_object-payment_method_collection and https://stripe.com/docs/payments/checkout/free-trials, this param will allow for trials that do not require a credit card.

I'm not sure how to build/test so someone may need to verify

Feature Request tracked in #476 - https://github.com/stripe/stripe-firebase-extensions/issues/476

2023-02-10 13:06 UTC, jsteele-stripe requested changes
Thanks for the submission! Couple of changes we should account for!

2023-02-10 13:06 UTC, jsteele-stripe commented on firestore-stripe-payments/functions/src/index.ts
> +      payment_method_collection
You probably want to set a default value (`always`) here to prevent potentially sending `null` values to the API.

2023-02-10 13:06 UTC, jsteele-stripe commented on firestore-stripe-payments/functions/src/index.ts
> +          payment_method_collection,
`payment_method_collection` parameter is only supported in `mode: 'subscription'` sessions, otherwise it'll error. We should prevent instances where this parameter may be passed for a `payment` session.

2023-03-13 03:10 UTC, prafuldivani commented
Hello @jsteele-stripe, 

I have incorporated the changes you suggested to my code. However, I have discovered that the type support requires upgrading the stripe package from version v8.191.0 to v10.2.0, which is a major upgrade. Can you please assist me with this upgrade?

![image](https://user-images.githubusercontent.com/40952264/224599509-c556205a-2504-49c0-9714-aec2a72523f3.png)

2023-03-20 10:52 UTC, closed without merging