feat(firestore-stripe-subscriptions): Add metadata support for price objects
stripe/stripe-firebase-extensions pull request #87
Opened 2020-10-29 22:37 UTC by ynnoj

Adds support for [`metadata`](https://stripe.com/docs/api/prices/object#price_object-metadata) on Price objects.

2020-10-29 22:37 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/stripe/stripe-firebase-extensions?pullRequest=87) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/stripe/stripe-firebase-extensions?pullRequest=87) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/stripe/stripe-firebase-extensions?pullRequest=87) it.</sub>

2020-10-29 22:38 UTC, ynnoj commented
@thorsten-stripe Hey Thor! Not sure what documentation you need me to add here.

2020-11-02 08:18 UTC, thorsten-stripe commented
Thanks @ynnoj. One question: do you see a benefit in syncing metadata rather than folks enriching data in their Firestore?

Two reason why I'd prefer not to sync the product & prices metadata:

1. We use the product metadata to set the `firebaseRole` which we extract to the `role` param on the product doc. Syncing the metadata means we'd have it double.
2. Pricing metadata can't be set via the Stripe Dashboard, so I don't see much value in syncing it.

Let me know if you have a good use case for syncing it though.

2020-11-02 12:34 UTC, ynnoj commented
@thorsten-stripe Thanks for your comments!

> do you see a benefit in syncing metadata rather than folks enriching data in their Firestore?

I was modelling products and variations using the product and (one-time) price objects. My intention was to use metadata as a way to display the variation information (size, colour, etc). Hadn't considered adding this data in the Firebase store.

> We use the product metadata to set the firebaseRole which we extract to the role param on the product doc. Syncing the metadata means we'd have it double.

We could assign the `firebaseRole` independently and then spread the remaining metadata to the Firebase doc. I can update the PR to reflect this.

> Pricing metadata can't be set via the Stripe Dashboard, so I don't see much value in syncing it.

This is true, which surprised me. But I've been updating it via the API for the use case described above.

2020-11-06 08:21 UTC, thorsten-stripe commented
@ynnoj sorry for the delay, I guess it is fair wanting Stripe to be the source of truth rather than needing to enrich data in Firestore.

> We could assign the firebaseRole independently and then spread the remaining metadata to the Firebase doc. I can update the PR to reflect this.

Yes, I think that's the right path forward, thanks.

Also great timing, as this will resolve https://github.com/stripe/stripe-firebase-extensions/issues/89

Thanks a mill for submitting :)

2020-11-06 08:33 UTC, thorsten-stripe commented on firestore-stripe-subscriptions/functions/src/index.ts
> +    metadata: product.metadata,
I think we have to remove `{ merge: true }` in the set method below for this to properly work. Otherwise it would always just add additional metadata without removing old entries.

2020-11-06 15:20 UTC, thorsten-stripe commented
Thanks @ynnoj I think this is good to go. Before I merge, I wanted to get your sense on making the metadata params top level params on the product doc with a `metadata_key` prefix, e.g. setting an `index` on the product metadata in the Stripe Dashboard would then translate to `metadata_index` on the product doc, rather than having the metadata map on the product.

I was thinking about this because of #90. Making these top level params on the doc would allow you to order products via Firebase, whereas if it is `metadata: { index: 1 }` you would have to do the sorting on the client. Wdyt? Am I overthinking this and folks are fine to do this sorting on the client?

2020-11-06 16:56 UTC, ynnoj commented
@thorsten-stripe Yes, I can see the advantages of flattening the `metadata` object on the Firestore object. I guess the prefix would be necessary to prevent any conflicts with 'native' Firestore fields. For example, if I added a `metadata.size` field to my Stripe product but also had `size` in my Firestore collection.

What about `stripe_metadata_[key]`?

2020-11-09 04:25 UTC, thorsten-stripe commented
Yes, exactly my thinking. `stripe_metadata_[key]` should be sufficient to avoid collision 👍 Mind updating the PR with that? Thanks a mill 💜

2020-11-09 09:59 UTC, thorsten-stripe commented
@ynnoj can rebase this PR to https://github.com/stripe/stripe-firebase-extensions/tree/firestore-stripe-subscriptions/v0.1.8 ? I've already added a changelog entry there for your changes: https://github.com/stripe/stripe-firebase-extensions/blob/firestore-stripe-subscriptions/v0.1.8/firestore-stripe-subscriptions/CHANGELOG.md#version-018---2020-11-19

No worries if it's too much trouble, then I'll merge your PR into `next` first and then rebase my PR (#96)

2020-11-09 11:17 UTC, ynnoj commented
@thorsten-stripe Will rebase if you're happy with that last commit 👍

2020-11-09 12:18 UTC, thorsten-stripe requested changes

2020-11-09 12:18 UTC, thorsten-stripe commented on firestore-stripe-subscriptions/functions/src/index.ts
> + const prefixedMetadataKeys = (metadata: object) =>
While I'm a big fan of the spreading magic, I think the following might be more readable:

```js
const prefixMetadata = (metadata: object) =>
  Object.keys(metadata).reduce((prefixedMetadata, key) => {
    prefixedMetadata[`stripe_metadata_${key}`] = metadata[key];
    return prefixedMetadata;
  }, {});
```

Wdyt?

Otherwise LGTM 👍

2020-11-09 12:37 UTC, ynnoj commented on firestore-stripe-subscriptions/functions/src/index.ts
> + const prefixedMetadataKeys = (metadata: object) =>
Will fix!

2020-11-09 13:25 UTC, merged

2021-03-02 16:52 UTC, dthib commented
Hi @ynnoj and @thorsten-stripe , as i am back to holidays I wanted to begin writing documentation on this choice but I was not confortable with this choice to be honest :)
I don't see the advantage of flattening metadata params: it's totally feasible to filter (with a where clause) and order result for nested fields (e.g. metadata.size). See:
- Order by: https://stackoverflow.com/questions/46840622/firestore-orderby-on-subproperty-subcollection
- Where clause: https://stackoverflow.com/questions/54857592/firestore-nested-query
I have done some testing to be sure of these posts as I haven't found firebase documentation for this and it's working well !

Is there any other advantages ?

To my mind, it's better to keep data structure as close as possible to stripe in order to have true mirroring (and avoid extra documentation effort).
Besides, if we keep metadata map, we have an homogeneous solution as metadata map is kept for subscription (see https://github.com/stripe/stripe-firebase-extensions/blob/next/firestore-stripe-subscriptions/functions/src/interfaces.ts#L102).

what do you think ? 
Best

2021-03-02 16:55 UTC, dthib commented
BTW, i was surprised not to be able to set price metadata in the dashboard but it's now possible.

2021-03-09 12:24 UTC, dthib commented
Hi,
@ynnoj  and @thorsten-stripe , any feedback ?
Thanks